services:
  azw-oai:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.azw-oai.tls=true"
      - "traefik.http.routers.azw-oai.tls.certresolver=default"
      - "traefik.http.routers.azw-oai.rule=Host(`oai-pmh.sammlung.azw.at`)"
      - "traefik.http.routers.azw-oai.entrypoints=http,https"

      - "traefik.http.services.azw-oai.loadbalancer.server.port=80"
      - "traefik.http.services.azw-oai.loadbalancer.server.scheme=http"
      
    networks:
      - "proxy"

networks:
  proxy:
    external: "true"

